---
deployment:
  tasks:
    - export DEPLOYPATH=/home/cctxay/apps/jgantts.com
    - export REPOPATH=/home/cctxay/repositories/jgantts.com
    - /bin/tsc
    - /bin/rm -rfv $DEPLOYPATH
    - /bin/cp -R $REPOPATH $DEPLOYPATH
    - /bin/touch DEPLOYPATH/tmp/restart.txt
