name: Build Vite App

on:
  push:
    branches: [ deploy-personal ]
  pull_request:
    branches: [ deploy-personal ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build Vite App
      run: npm run build

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/