name: Deploy to Linode

on:
  push:
    branches:
      - prod

jobs:
  changes:
    runs-on: ubuntu-latest

    outputs:
      maps_sources: ${{ steps.filter.outputs.maps_sources }}

    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            maps_python:
              - 'python/**'
            maps_sources:
              - 'maps-sources/**'
            website:
              - 'jgantts-com/**'

  deploy-maps:
    needs: changes
    if: needs.changes.outputs.maps_python == 'true' |
      || needs.changes.outputs.maps_sources == 'true'
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            python:
              - 'python/**'
            maps_sources:
              - 'jgantts-com/PUBLIC/assets/kovyalo/geo-data/**'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PMTiles CLI
        run: |
          mkdir -p $HOME/.local/bin
          curl -fL https://github.com/protomaps/go-pmtiles/releases/download/v1.30.2/go-pmtiles_1.30.2_Linux_x86_64.tar.gz -o pmtiles.tar.gz
          tar -xzf pmtiles.tar.gz
          chmod +x pmtiles
          mv pmtiles $HOME/.local/bin/pmtiles
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Verify tools
        run: |
          gdalwarp --version
          gdal2tiles.py --help
          pmtiles --help

      - name: Install Python dependencies
        run: |
          python3 -m venv ./venv
          source ./venv/bin/activate
          python3 -m pip install -r requirements.txt
        working-directory: ./python/

      - name: Build map
        run: |
          python3 -m venv ./venv
          source ./venv/bin/activate
          python3 make_all_tiles.py
        working-directory: ./python/

      - name: Deploy Map
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.LINODE_IP }}
          username: ${{ secrets.LINODE_USER }}
          password: ${{ secrets.LINODE_PASSWORD }}
          port: 22
          source: './maps-rendered/'
          target: '/home/jgantts-com/node-js/jgantts-com/PUBLIC/assets/maps/'
          strip_components: 2
          rm: true

  deploy-site:
    needs: changes
    if: needs.changes.outputs.website == 'true'
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            website:
              - 'jgantts-com/**'

      - name: build
        run: |
          npm i
          npm run build
        working-directory: ./jgantts-com/

      - name: Deploy JGantts Server
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.LINODE_IP }}
          username: ${{ secrets.LINODE_USER }}
          password: ${{ secrets.LINODE_PASSWORD }}
          port: 22
          source: './jgantts-server/*,./jgantts-com/dist/*,./jgantts-com/PUBLIC/*'
          target: '/home/jgantts-com/node-js/'

      - name: Restart JGantts Server
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.LINODE_IP }}
          username: ${{ secrets.LINODE_USER }}
          password: ${{ secrets.LINODE_PASSWORD }}
          port: 22
          script: |
            whoami
            cd /home/jgantts-com/node-js/jgantts-server
            npm install --omit=dev
            sudo systemctl restart jgantts-com-node-app
