name: Deploy to Linode

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm i
        working-directory: ./app/

      - name: build
        run: |
          npm run build
        working-directory: ./app/

      - name: Deploy JGantts Server
        uses: appleboy/scp-action@v0.1.2
        with:
          host: ${{ secrets.LINODE_IP }}
          username: ${{ secrets.LINODE_USER }}
          key: ${{ secrets.LINODE_SSH_KEY }}
          port: 22
          source: './jgantts-server/*'
          target: '/opt/nodejs/jgantts-server'

      - name: Deploy Static Site
        uses: appleboy/scp-action@v0.1.2
        with:
          host: ${{ secrets.LINODE_IP }}
          username: ${{ secrets.LINODE_USER }}
          key: ${{ secrets.LINODE_SSH_KEY }}
          port: 22
          source: './jgantts-com/dist/*'
          target: '/opt/nodejs/jgantts-com/dist'

      - name: Deploy Static Site
        uses: appleboy/scp-action@v0.1.2
        with:
          host: ${{ secrets.LINODE_IP }}
          username: ${{ secrets.LINODE_USER }}
          key: ${{ secrets.LINODE_SSH_KEY }}
          port: 22
          source: './jgantts-com/PUBLIC/*'
          target: '/opt/nodejs/jgantts-com/PUBLIC'
