name: Deploy to Linode

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: run python scripts
        run: |
          python3 -m venv ./venv
          source ./venv/bin/activate
          python3 -m pip install -r requirements.txt
          python3 tile_dem.py
        working-directory: ./python/

      - name: build
        run: |
          npm i
          npm run build
        working-directory: ./jgantts-com/

      - name: Deploy JGantts Server
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.LINODE_IP }}
          username: ${{ secrets.LINODE_USER }}
          password: ${{ secrets.LINODE_PASSWORD }}
          port: 22
          source: './jgantts-server/*,./jgantts-com/dist/*,./jgantts-com/PUBLIC/*'
          target: '/home/jgantts-com/node-js/'

      - name: Restart JGantts Server
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.LINODE_IP }}
          username: ${{ secrets.LINODE_USER }}
          password: ${{ secrets.LINODE_PASSWORD }}
          port: 22
          script: |
            whoami
            cd /home/jgantts-com/node-js/jgantts-server
            npm install --omit=dev
            sudo systemctl restart jgantts-com-node-app
