name: Deploy to Linode

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm i
        working-directory: ./jgantts-com/

      - name: build
        run: |
          npm run build
        working-directory: ./jgantts-com/

      - name: Deploy JGantts Server
        uses: appleboy/scp-action@v0.1.2
        with:
          host: ${{ secrets.LINODE_IP }}
          username: ${{ secrets.LINODE_USER }}
          password: ${{ secrets.LINODE_PASSWORD }}
          port: 22
          source: './jgantts-server/*,./jgantts-com/dist/*,./jgantts-com/PUBLIC/*'
          target: '/home/jgantts-com/node-js/'

      - name: Restart JGantts Server
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.LINODE_IP }}
          username: ${{ secrets.LINODE_USER }}
          password: ${{ secrets.LINODE_PASSWORD }}
          port: 22
          script: |
            cd /home/jgantts-com/node-js/jgantts-com
            npm install --production
            cd /home/jgantts-com/node-js/jgantts-server
            npm install --production
            pm2 restart jgantts-server
