# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Clone JGantts/poc-github-actions PUBLIC repository
      uses: GuillaumeFalourd/clone-github-repo-action@v2
      with:
        owner: 'JGantts'
        repository: 'jgantts.com'
    - uses: jgantts/action-jgantts.com@v1
      with:
        milliseconds: 1000
        namecheap_domain: jgantts.com
        namecheap_username: ${{ matrix.NAMECHEAP_USERNAME }}
        namecheap_ssh_key: ${{ matrix.NAMECHEAP_SSH_KEY }}
        namecheap_ssh_port: ${{ matrix.NAMECHEAP_SSH_PORT }}
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        registry-url: https://npm.pkg.github.com/
    - run: npm ci
    env:
      NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
